use crate::model::{PackageSpec, safe_path, target};
use anyhow::{Context, Result, ensure};
use clap::Args;
use semver::Version;
use std::{collections::BTreeMap, fs, io::Write, path::PathBuf};

/// Create an editable manifest for a program you have already built.
#[derive(Args)]
#[group(id = "init")]
pub struct InitArgs {
    #[arg(long)]
    pub name: String,
    #[arg(long, default_value = "0.1.0")]
    pub version: Version,
    /// Directory containing only the files to distribute.
    #[arg(long, default_value = "stage")]
    pub payload: PathBuf,
    /// Executable path relative to the payload, such as bin/hello or bin/hello.exe.
    #[arg(long, required_unless_present = "app", conflicts_with = "app")]
    pub command: Option<String>,
    /// macOS application bundle path relative to the payload.
    #[arg(long)]
    pub app: Option<String>,
    /// Defaults to this machine's target; choose the platform you built for.
    #[arg(long)]
    pub target: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    /// New manifest path, outside the payload. Existing files are never replaced.
    #[arg(long, default_value = "haps.toml")]
    pub out: PathBuf,
    #[arg(long)]
    pub json: bool,
}

pub fn create(args: &InitArgs) -> Result<PackageSpec> {
    let spec = PackageSpec {
        name: args.name.clone(),
        version: args.version.clone(),
        target: args.target.clone().unwrap_or_else(|| target().into()),
        description: args
            .description
            .clone()
            .unwrap_or_else(|| args.name.clone()),
        commands: args
            .command
            .as_ref()
            .map(|p| BTreeMap::from([(args.name.clone(), p.clone())]))
            .unwrap_or_default(),
        app: args.app.clone(),
        desktop: None,
        source: None,
    };
    spec.validate()?;
    let payload = args
        .payload
        .canonicalize()
        .context("payload directory does not exist")?;
    ensure!(payload.is_dir(), "payload must be a directory");
    let entry = args
        .command
        .clone()
        .or_else(|| {
            args.app
                .as_ref()
                .map(|app| format!("{app}/Contents/Info.plist"))
        })
        .context("specify --command or --app")?;
    let relative = safe_path(&entry)?;
    let mut path = payload.clone();
    for component in relative.components() {
        path.push(component);
        ensure!(
            !fs::symlink_metadata(&path)
                .with_context(|| format!("missing payload entry: {entry}"))?
                .file_type()
                .is_symlink(),
            "payload entry cannot contain symlinks: {entry}"
        );
    }
    ensure!(
        path.is_file(),
        "payload entry must be a regular file: {entry}"
    );
    let parent = args
        .out
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .unwrap_or_else(|| std::path::Path::new("."));
    let parent = parent
        .canonicalize()
        .context("manifest output directory does not exist")?;
    ensure!(
        !parent.starts_with(&payload),
        "write the manifest outside the payload"
    );
    let name = args
        .out
        .file_name()
        .context("manifest output must name a file")?;
    let mut file = tempfile::NamedTempFile::new_in(&parent)?;
    writeln!(
        file,
        "# Generated by haps init. Edit metadata before packing.\n{}",
        toml::to_string_pretty(&spec)?
    )?;
    file.as_file().sync_all()?;
    file.persist_noclobber(parent.join(name))
        .context("could not create manifest; existing files are never replaced")?;
    Ok(spec)
}
